"""Generate static HTML config dump for Playwright screenshot."""
import html
from pathlib import Path
from config import get_config


def main():
    """Generate config dump HTML file."""
    cfg = get_config()
    dump_text = cfg.dump()
    json_text = cfg.dump_json()
    env_name = cfg.environment.value

    page_html = f"""<!DOCTYPE html>
<html>
<head>
    <title>ENG-25: Centralized Config</title>
    <style>
        body {{
            font-family: monospace;
            background: #1a1a2e;
            color: #e0e0e0;
            padding: 20px;
            margin: 0;
        }}
        h1 {{
            color: #00d4ff;
            border-bottom: 2px solid #00d4ff;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #ff6b6b;
            margin-top: 30px;
        }}
        .badge {{
            display: inline-block;
            padding: 4px 12px;
            border-radius: 4px;
            font-weight: bold;
            margin-left: 10px;
        }}
        .badge-development {{
            background: #2d5a3d;
            color: #4ade80;
        }}
        .badge-staging {{
            background: #5a4a2d;
            color: #fbbf24;
        }}
        .badge-production {{
            background: #5a2d2d;
            color: #f87171;
        }}
        pre {{
            background: #16213e;
            padding: 16px;
            border-radius: 8px;
            overflow-x: auto;
            border: 1px solid #333;
            line-height: 1.6;
        }}
        .section {{
            margin-bottom: 24px;
        }}
        .status {{
            padding: 12px;
            border-radius: 8px;
            margin-bottom: 16px;
        }}
        .status-ok {{
            background: #1a3a2a;
            border: 1px solid #4ade80;
            color: #4ade80;
        }}
        .tests {{
            background: #1a2a3a;
            border: 1px solid #60a5fa;
            color: #60a5fa;
            padding: 12px;
            border-radius: 8px;
            margin-bottom: 16px;
        }}
        .meta {{
            color: #888;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <h1>ENG-25: Centralized Config
        <span class="badge badge-{env_name}">{env_name.upper()}</span>
    </h1>

    <div class="status status-ok">
        Configuration loaded and validated successfully via Pydantic Settings.
    </div>

    <div class="tests">
        Validation tests: 13/13 passed (URL format, enum values, bounds, secrets masking, derived properties)
    </div>

    <div class="section">
        <h2>Config Dump (Text)</h2>
        <pre>{html.escape(dump_text)}</pre>
    </div>

    <div class="section">
        <h2>Config Dump (JSON)</h2>
        <pre>{html.escape(json_text)}</pre>
    </div>

    <div class="section">
        <h2>Derived Properties</h2>
        <pre>orchestrator_model_id: {html.escape(cfg.orchestrator_model_id)}
is_production: {cfg.is_production}
is_development: {cfg.is_development}
telegram_configured: {cfg.telegram_configured}
mcp_auth_headers: {html.escape(str(bool(cfg.mcp_auth_headers)))}
github_reviewers_list: {html.escape(str(cfg.github_reviewers_list))}</pre>
    </div>

    <p class="meta">
        Generated by test_config_html.py | config.py module (ENG-25)
    </p>
</body>
</html>"""

    output_path = Path("test_config_output.html")
    output_path.write_text(page_html)
    print(f"Generated: {output_path.resolve()}")


if __name__ == "__main__":
    main()
